package changelog

import "strings"

// Header is the preamble written to a CHANGELOG.md that does not exist yet.
const Header = `# Changelog

All notable changes to this project are documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

This file is generated by ` + "`go run ./cmd/release changelog`" + ` and should not be edited by hand.
`

// Insert places a rendered entry into an existing CHANGELOG.md, immediately
// above the most recent version heading so that the newest release stays at the
// top.
//
// It returns changed=false when the file already documents that version, which
// makes re-running the release workflow for a tag a no-op rather than a
// duplicate entry.
func Insert(existing []byte, version, entry string) (updated []byte, changed bool) {
	content := string(existing)
	if strings.Contains(content, "## ["+version+"]") {
		return existing, false
	}
	entry = strings.TrimRight(entry, "\n")

	if strings.TrimSpace(content) == "" {
		return []byte(Header + "\n" + entry + "\n"), true
	}

	lines := strings.Split(content, "\n")
	insertAt := -1
	for i, line := range lines {
		if strings.HasPrefix(line, "## ") {
			insertAt = i
			break
		}
	}
	if insertAt == -1 {
		// A preamble with no releases yet: append after it.
		return []byte(strings.TrimRight(content, "\n") + "\n\n" + entry + "\n"), true
	}

	preamble := strings.TrimRight(strings.Join(lines[:insertAt], "\n"), "\n")
	rest := strings.Join(lines[insertAt:], "\n")
	return []byte(preamble + "\n\n" + entry + "\n\n" + rest), true
}
