package changelog

import (
	"fmt"
	"strings"
)

// summaryClause maps a category onto the phrase it contributes to the summary.
// Order matters: it is the order a reader cares about.
var summaryClauses = []struct {
	key      string
	verb     string
	singular string
	plural   string
}{
	{"feat", "introduces", "new feature", "new features"},
	{"fix", "fixes", "bug", "bugs"},
	{"perf", "improves", "performance improvement", "performance improvements"},
	{"refactor", "reworks", "internal change", "internal changes"},
	{"docs", "documents", "change", "changes"},
}

// Summary is a one-paragraph description of what a release contains, placed
// above the changelog so a reader knows whether to keep reading.
//
// It is assembled from the commit counts, never from the commit text. A summary
// generated by paraphrasing subjects would eventually describe a release
// inaccurately, and nobody would notice before it was published. Counting is
// dull and correct, which is the right trade for a release note.
//
// An empty release yields an empty string, so the caller can omit the paragraph
// rather than print a sentence about nothing.
func Summary(stats Stats) string {
	if stats.Commits == 0 {
		return ""
	}

	var parts []string
	for _, clause := range summaryClauses {
		if n := count(stats, clause.key); n > 0 {
			parts = append(parts, clause.verb+" "+quantity(n, clause.singular, clause.plural))
		}
	}

	var b strings.Builder
	b.WriteString("This release ")
	if len(parts) == 0 {
		// Only housekeeping. Say so, rather than claiming nothing happened.
		fmt.Fprintf(&b, "contains %s.", quantity(stats.Commits, "change", "changes"))
		return b.String()
	}
	b.WriteString(list(parts))
	b.WriteString(".")

	if stats.Breaking > 0 {
		fmt.Fprintf(&b, " It contains %s, so review the notes before upgrading.",
			quantity(stats.Breaking, "breaking change", "breaking changes"))
	}
	return b.String()
}

// count returns how many commits a category holds.
func count(stats Stats, key string) int {
	for _, c := range stats.Counts {
		if c.Key == key {
			return c.N
		}
	}
	return 0
}

// quantity renders "1 bug" or "3 bugs".
func quantity(n int, singular, plural string) string {
	if n == 1 {
		return fmt.Sprintf("%d %s", n, singular)
	}
	return fmt.Sprintf("%d %s", n, plural)
}

// list joins clauses the way English does: "a", "a and b", "a, b, and c".
func list(parts []string) string {
	switch len(parts) {
	case 1:
		return parts[0]
	case 2:
		return parts[0] + " and " + parts[1]
	default:
		return strings.Join(parts[:len(parts)-1], ", ") + ", and " + parts[len(parts)-1]
	}
}
