package release

import (
	"fmt"

	"github.com/teddynted/designing-an-ai-agent-platform-on-aws/internal/git"
	"github.com/teddynted/designing-an-ai-agent-platform-on-aws/internal/version"
)

// NotesService assembles release notes from a comparison.
type NotesService struct {
	comparisons *ComparisonService
	clock       Clock

	// IncludeSHA appends the abbreviated commit to each entry.
	IncludeSHA bool
}

// NewNotesService builds the service. A nil clock uses the system clock.
func NewNotesService(comparisons *ComparisonService, clock Clock) *NotesService {
	if clock == nil {
		clock = SystemClock{}
	}
	return &NotesService{comparisons: comparisons, clock: clock, IncludeSHA: true}
}

// Generate builds the notes for target by comparing it against its predecessor.
//
// head names the ref to diff: the release tag once it exists, and HEAD before it
// does — which is the ordinary case, since notes are written before the tag is
// pushed.
func (s *NotesService) Generate(target version.Version, head string) (Notes, error) {
	comparison, err := s.comparisons.CompareRelease(target, head)
	if err != nil {
		return Notes{}, fmt.Errorf("could not compare %s against its predecessor: %w", target.Tag(), err)
	}
	return s.FromComparison(target, comparison), nil
}

// FromComparison builds notes from an already-computed comparison. Split out so
// that a caller holding a comparison need not fetch it twice.
func (s *NotesService) FromComparison(target version.Version, comparison git.Comparison) Notes {
	// The comparison is about target, whatever ref was diffed to produce it.
	// Without this, notes generated by diffing HEAD would render a compare link
	// naming the ref rather than the release being cut.
	comparison.Head = target

	sections := map[Category][]string{}
	for _, classified := range ClassifyAll(comparison.Commits) {
		category := classified.Category
		sections[category] = append(sections[category], classified.Entry(s.IncludeSHA))
	}

	return Notes{
		Version:    target,
		Date:       s.clock.Today(),
		Summary:    summarise(comparison),
		Sections:   sections,
		Comparison: &comparison,
	}
}

// summarise states the size of the release in one sentence. It reports facts —
// counts — rather than characterising the release, which is the author's job.
func summarise(c git.Comparison) string {
	if c.IsInitial() {
		return fmt.Sprintf(
			"Initial release. %s across %s.",
			plural(c.CommitCount(), "commit", "commits"),
			plural(c.FileCount(), "file", "files"),
		)
	}
	return fmt.Sprintf(
		"%s across %s, with %d insertions and %d deletions.",
		plural(c.CommitCount(), "commit", "commits"),
		plural(c.FileCount(), "file", "files"),
		c.Insertions(),
		c.Deletions(),
	)
}

func plural(n int, singular, many string) string {
	if n == 1 {
		return fmt.Sprintf("%d %s", n, singular)
	}
	return fmt.Sprintf("%d %s", n, many)
}
